### ISSUE TITLE
Admin Fact Sheet broken link

### ISSUE THREAD

**Issue by danielvi1787** [ProvisionGenie/ProvisionGenie#45]
**Describe the incompleteness or inaccuracy**
In the Admin Fact Sheet page the link to Architecture Decisions is broken, it points to https://github.com/ProvisionGenie/ProvisionGenie/blob/main/Docs/Docs/ArchitectureDecisions.md but should points to https://github.com/ProvisionGenie/ProvisionGenie/blob/main/Docs/ArchitectureDecisions.md

**Comment by LuiseFreese** [comment]
Would you like to fix it? You'd have the honor of the first PR after release 🧞

**Comment by danielvi1787** [comment]
> Would you like to fix it? You'd have the honor of the first PR after release 🧞

My pleasure!

**Comment by LuiseFreese** [comment]
merged 🎉
