### ISSUE TITLE
[Deployment] Provide automation for setting up the resource group and storage account

### ISSUE THREAD

**Issue by gavinbarron** [ProvisionGenie/ProvisionGenie#48]
## Automation for Resource Group and Storage Account

Currently the person deploying the solution needs to manually create the hosting resource group and storage account to hold the arm templates for deployment.

It would be nice if this were automated to reduce the deployment friction.

**Comment by LuiseFreese** [comment]
thank you again, @gavinbarron ! Great work 🚀🚀🚀
