### ISSUE TITLE
[Deployment] Automate creation of AAD App Registration

### ISSUE THREAD

**Issue by gavinbarron** [ProvisionGenie/ProvisionGenie#49]
## Automate creation of AAD App Registration

Currently the user performing deployment of this solution needs to manually create the AAD Application in the portal.

It might be nice to provide a script to give users an automated option for this part of the deployment process
This should be achievable using https://docs.microsoft.com/en-us/cli/azure/ad/app?view=azure-cli-latest

**Comment by LuiseFreese** [comment]
collaborating with you is an amazing experience, thank you dear friend @gavinbarron
