### ISSUE TITLE
[Deployment] Provide scripts as scripts with parameters

### ISSUE THREAD

**Issue by gavinbarron** [ProvisionGenie/ProvisionGenie#50]
## Provide deployment scripts read to run options

Currently the scripts for deployment are inline in the markdown. This is great for reading. It might be a good idea to have all the scripts collected into a scripts folder so that users can run scripts with parameters rather than needing to copy/paste and build their own scripts from the docs.

**Comment by LuiseFreese** [comment]
you truly amazed me with your patience, consistency and dedication to get things moving.
