### ISSUE TITLE
Azure automation toolset?

### ISSUE THREAD

**Issue by gavinbarron** [ProvisionGenie/ProvisionGenie#51]
In the docs there is use of both PowerShell modules and Azure CLI commands.

There are times when we have to choose one tool because it offers features or command surface area that the other does not it appears to me that everything that is being done in script at the moment could be done purely in Azure CLI. Possibly in using PowerShell modules, but TBH I'm not that well versed in the Azure AD PowerShell modules.

Is there a preferred toolset for this project? 
Should the project care?

(Please forgive the flurry of issues, I think that this stuff is super cool and I'm looking to offer my help)

**Comment by LuiseFreese** [comment]
you really excel at scripts AND open-source and its a pleasure to have you as a contributor. Let me know your T-shirt size 💙
