### ISSUE TITLE
This is awesome

### ISSUE THREAD

**Issue by arielkropp** [ProvisionGenie/ProvisionGenie#68]
I can't believe you are giving this away for free - taking community spirit to a new level.

One thing worth adding (not to toot my own horn or anything) in [this](https://provisiongenie.com/architecturedecisions/#no-microsoft-planner-provisioning) section you could add a link to vote for the [idea](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/application-permissions-for-planner-apis/idi-p/2266449)

**Comment by LuiseFreese** [comment]
Dear @arielkropp - thank you for your kind feedback - We are all very happy to show community love with ProvisionGenie 🧞

I included a link to your idea here: 

https://provisiongenie.com/architecturedecisions/#consequences-of-not-provisioning-planner

Thank you for contributing 💜
