### ISSUE TITLE
error running the deployment SP script to create App registration

### ISSUE THREAD

**Issue by xundong** [ProvisionGenie/ProvisionGenie#75]
**Describe the bug**
Ran ./Create-AadAppRegistration.ps1 -SubscriptionId "mysubscription id" -AadAppName ProvisionGenieApp
Got error 
Operation failed with status: 'Bad Request'. Details: 400 Client Error: Bad Request for url: https://graph.windows.net/MYTenantID/oauth2PermissionGrants?api-version=1.6

The "ProvisionGenieApp" app reg is created, but I guess it's not fully configured.

**To Reproduce**
1. Open Cloud Shell PowerShell from my Azure Portal in Edge
2. following your deployment guid by done a git clone 
3. the move to the script dir and ran the ./Create-AadAppRegistration.ps1 

**Expected behavior**

**Screenshots**
See the attached screenshots for What has been created by the script so far.
![image](https://user-images.githubusercontent.com/33489013/149547387-11e4266a-7951-4824-970c-39451f3b5534.png)
![image](https://user-images.githubusercontent.com/33489013/149546743-02c86c7e-182a-4678-9643-df69d2077174.png)

**Additional context**
Finally meanwhile, could please let me know the details re how to configure the App Reg, so I could carry on getting it there manually, please?

**Comment by LuiseFreese** [comment]
Hi there, thanks for getting in touch. Can you tell me the specific error or what makes you think that the app is not fully configured? 

After this app registration, you will need to continue with deploying ProvisionGenie as in importing  the Power Platform solution and then deploying the Logic Apps and assigning permissions to the Managed Identity. This is explained here: [Deployment steps clean install](https://provisiongenie.com/deploymentguide/#deployment-steps-clean-install) 

Please let us know how it works for you.

**Comment by xundong** [comment]
Hello, thanks for quick response.

Yes after the script was executed, I get an error in the cloud shell
Operation failed with status: 'Bad Request'. Details: 400 Client Error: Bad Request for url: https://graph.windows.net/[MYTenantID]/oauth2PermissionGrants?api-version=1.6


![image](https://user-images.githubusercontent.com/33489013/149562133-4322d3fd-9756-4a7e-b9cb-e0d8484904ee.png)

If you have the instruction on how to create the App Reg manually I will try whiles you take a look of the error...?

**Comment by YannickRe** [comment]
It looks like only the last step of the script is failing. If you go to your App Registration -> find your app -> API permissions and click the "Grant admin consent for ..." button, that does what the last line of the script does as well.

At the moment we cannot reproduce (2 of us tried), so I have questions:
- Are you in public cloud, sovereign cloud or government cloud?
- Could you run an `az --version` in Cloud Shell and show me the output?
- What region is your Azure AD in? 
![image](https://user-images.githubusercontent.com/9973962/149578686-679700a3-a6a5-4d03-9123-beb37442a449.png)
- The user that's executing, which roles does it have on Azure AD (Global Admin?) and on the subscription?

I also made a casing adjustment to the script, could you be so kind to check if the new version might fix the problem you are having?

**Comment by xundong** [comment]
Hiya, many thanks for getting back to me so quickly.

I have just manually tried to "Grant admin consent" on the App Reg that was created by the script.
I getting the following error, 
"Could not grant admin consent. Your organization does not have a subscription (or service principal) for the following API(s): Dynamics CRM "
which makes perfect sense now. As this I don't have a Power App license there...
My bad. Next week I will run the script in our dev tenant where I will relevant licenses required.
Should be fine then.
I will close this issue now. cheers
